site_name: Guia para Tópicos I
theme:
  name: material

nav:
  - Início: index.md
  - Seção 1: 
    - Seção 1: secao-1/secao-1.md
    - Seção 1-1: secao-1/secao-1-1.md
    - Seção 1-2: secao-1/secao-1-2.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
